package midoku:example-source;

interface api {
    use midoku:types/types.{chapter, manga, page};

    get-manga-list: func(page: u32) -> result<tuple<list<manga>, bool>>;
    get-manga-details: func(manga-id: string) -> result<manga>;
    get-chapter-list: func(manga-id: string) -> result<list<chapter>>;
    get-page-list: func(manga-id: string, chapter-id: string) -> result<list<page>>;
}

world endpoints {
    export midoku:types/types;

    export api;
}
