package midoku:example-source;

use midoku:midoku-types/chapter;
use midoku:midoku-types/manga;
use midoku:midoku-types/page;

world prelude {
    import midoku:midoku-http/http;

    use chapter.{chapter};
    use manga.{manga, page-result};
    use page.{page};

    export get-manga-list: func(page: u32) -> result<page-result>;
    export get-manga-details: func(manga-id: string) -> result<manga>;
    export get-chapter-list: func(manga-id: string) -> result<list<chapter>>;
    export get-page-list: func(manga-id: string, chapter-id: string) -> result<list<page>>;
}
