[package]
name = "midoku-types"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
wasmtime = "20.0.0"
witgen_macro = "0.15.0"

[build-dependencies]
anyhow = "1.0.82"
cargo-witgen = "0.15.0"
