interface manga {
    enum status {
        unknown,
        ongoing,
        completed,
        hiatus,
        cancelled,
    }

    enum content-rating {
        safe,
        suggestive,
        nsfw,
    }

    enum reading-mode {
        right-to-left,
        left-to-right,
        vertical,
        scroll,
    }

    record manga {
        id: string,
        title: string,
        url: string,
        description: string,
        cover-url: string,
        author-name: string,
        artist-name: string,
        categories: list<string>,
        status: status,
        content-rating: content-rating,
        reading-mode: reading-mode,
    }

    record page-result {
        page: list<manga>,
        has-more: bool,
    }
}
