[package]
name = "midoku-http"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
wasmtime = "20.0.0"
