[package]
name = "midoku-http"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
futures = "0.3.30"
governor = { version = "0.6.3", default-features = false, features = ["std"] }
reqwest = "0.12.3"
wit-bindgen-rt = "0.24.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "midoku:midoku-http"
