[package]
name = "midoku-limiter"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
governor = { version = "0.8.0", default-features = false, features = ["std"] }

[dev-dependencies]
tokio.workspace = true
