name: Cargo test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests

    env:
      CARGO_COMPONENT_VERSION: "0.20.0"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install wasm32-unknown-unknown target
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-component
        run: cargo-binstall cargo-component --locked --version $CARGO_COMPONENT_VERSION --force --no-confirm

      - name: Run `cargo test`
        run: cargo test --workspace --exclude example-extension

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run `cargo fmt`
        run: cargo fmt --all -- --check
